# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    linux_swift_4.1:
      docker:
        - image: norionomura/swift:41
      steps:
        - checkout
        - run: swift build
        - run: swift test
